# Data parameters
data:
    dataset: cifar10
    data_dir: data/cifar10-data
    input_size: [32,32]
    input_channels: 3
    num_classes: 10
    valid_size: 0.1

# Training parameters
training:
    output_folder: results/logs/cifar10/cifar10_resnet32_pretrained
    task: classification
    learner: default
    nb_epochs: 200
    batch_size: 128
    loss:
        name: cross_entropy
    optimizer:
        name: sgd
        lr: 0.1
        momentum: 0.9
        weight_decay: 0.0001
    lr_schedule:
        name: multi_step
        milestones: [100, 150]
    metrics: ['accuracy', 'auc', 'ap_success', 'ap_errors']
    pin_memory: False
    num_workers: 3
    augmentations:
        hflip: True
        random_crop: 32
        normalize: [[0.485, 0.456, 0.406], [0.229, 0.224, 0.225]]

# Model parameters
model:
    name: resnet32
    resume: 
