# Data parameters
data:
    dataset: mnist
    data_dir: data/mnist-data
    input_size: [28,28]
    input_channels: 1
    num_classes: 10
    valid_size: 0.1

# Training parameters
training:
    output_folder: results/logs/mnist/mnist_selfconfid
    task: classification
    learner: selfconfid
    nb_epochs: 500
    batch_size: 128
    loss:
        name: selfconfid_mse
        weighting: 1
    optimizer:
        name: adam
        lr: 0.0001
    lr_schedule:
    ft_on_val: False
    metrics: ['accuracy', 'auc', 'ap_success', 'ap_errors']
    pin_memory: False
    num_workers: 3
    augmentations:
        normalize: [[0.1307,], [0.3081,]]

# Model parameters
model:
    name: small_convnet_mnist_selfconfid_classic
    resume: results/logs/mnist/mnist_pretrained/model_epoch_064.ckpt
    
